### ISSUE TITLE
Blackberry OS10 adaption? App closes by itself.

### ISSUE THREAD

**Issue by Ricci1969** [Antox/Antox#350] opened 2016-10-06 14:19 UTC
On my Blackberry Z30: 
Can't register or import my pc profile. After touching "Register" or selecting my profile.tox file in the file-explorer the app closes by itself. 

![img_20161006_154846](https://cloud.githubusercontent.com/assets/22661715/19155398/9ca6c496-8bde-11e6-9217-e421aa5df3fd.png)

![img_20161006_161046](https://cloud.githubusercontent.com/assets/22661715/19155802/1c5fad96-8be0-11e6-9cd6-bdd82601c95d.png)

**Comment by subliun** [comment] 2017-01-09 07:35
Duplicate of #92

**Closed by subliun** 2017-01-09 07:35 UTC
