### ISSUE TITLE
1GB of Background Data Usage during the night

### ISSUE THREAD

**Issue by ElectricPrism** [Antox/Antox#363] opened 2016-11-09 01:33 UTC
So I woke up and 40% of my data usage was gone. Antox decided to use 1.1GB of data in the night.

What the fuck? Seriously... what the actual fuck?

Brainstorm please.

**Comment by scarf** [comment] 2016-11-10 02:31
same thing happened to me, although it was only 45MB.  still enough to make me look this up.  i disabled background data for the app for now

**Comment by Steffov** [comment] 2016-11-13 10:24
I can confirm the issue. 22,5 MB background data during 1 or 2 hours. Transmitted some words to a contact but most time was standby.

Do anyone knows what data were transmitted? 

Android: 5.1.1
Antox: 0.24.422

**Comment by ElectricPrism** [comment] 2016-12-02 15:27
@Steffov the only way I could imagine figuring it out would be to set up a middle man Linux server broadcasting a wifi SSID and caching all traffic coming through and running that through a analysis app assuming it happens periodically and not only as a one-time thing.

Somethings fucky.

**Comment by GitHubHatesTor** [comment] 2016-12-15 02:00
This is a P2P app. You(A) connect to B, C, and D to make a stable connection.
Even you have no contact to talk, this app will make a stable connection to all of them to let
tox network know you're online/away/busy(share status/user info).

Therefore, if you're looking for low-battery consumption app;
a. Convince the Antox developer to make a connection only ONE node. This will provide less anonymity if you don't use Orbot.(A->B,C,and D ===> A->B only)
b. Convince the developer to implement taffic limit(e.g., 100-500kb/s)
c. Force app into sleep mode when any network is not active (related: Orbot's No network sleep function)
d. Or, use XMPP & "Conversations" app. (Client-Server app)

**Comment by christianweinz** [comment] 2016-12-21 02:36
A P2P program does not necessarily have a lot of connections open. It just means that the connection between the clients is direct.

Tox uses the many connections with constant traffic to connect to the DHT. To have direct communication with my peers, contact to the DHT is not always needed.

Maybe, after fetching the contacts connection details, Antox should make stop Toxcore from talking to anything continuously. Just listen at the appropriate ports for connections, or build one when we want to initiate a communication. On connection error we can fallback to ask the DHT for updated IP's or, in the future,  leave offline messages.

In principle, there is no need for every client to participate continuously in the DHT.

**Comment by subliun** [comment] 2017-01-09 07:33
Duplicate of #6

**Closed by subliun** 2017-01-09 07:33 UTC
