### ISSUE TITLE
Audio out issue

### ISSUE THREAD

**Issue by reallynoclueabout** [Antox/Antox#395] opened 2017-01-23 15:09 UTC
This is my first post here, so a big first hello to the community

I'm a mobile newbie, my device is a Sony Xperia Z3 Tablet 8'' Compact (6.0 Marshmallow). Yesterday I downloaded the Antox app, but unfortunately it was not possible to use the app properly. When I tried to talk with someone, I could hear his voice, but he not mine. The audio sign on display was sometimes off, sometimes on, but always without my voice.

I'd like to know, if the problem is related generally to my device or is the result of technical issues and bugs.

Thanks for answers, J. T.

**Comment by anon8675309** [comment] 2017-02-11 06:06
Hello @reallynoclueabout.  It does seem to be related to the device.  It looks like you are facing the same issue as me and at least two other people.  First, grab the latest version from the Play store that was released yesterday and see if that fixes your issue.  If not, follow along with https://github.com/Antox/Antox/issues/409.

In any case, this issue can be closed as a duplicate of #409.

**Comment by wiiaam** [comment] 2017-02-17 08:23
Hey @reallynoclueabout thanks for reporting the issue, I will be investigating issues with audio calls as soon as I get back from the other side of the country. For now though, discussion on this can be made on this issue: https://github.com/Antox/Antox/issues/409

**Closed by wiiaam** 2017-02-17 08:23 UTC
Labels: bug

**Comment by reallynoclueabout** [comment] 2017-02-23 21:45
Dear @wiiaam and @anon8675309, thank you for the replies. Best wishes for your future efforts
