### ISSUE TITLE
Antox crash on login

### ISSUE THREAD

**Issue by Grokafar** [Antox/Antox#407] opened 2017-02-07 22:35 UTC
Antox version 0.25.452 from fdroid crash on login. I've tried to delete all application's datas but the problem still the same. 
Step to reproduce
Force stop antox
Clear data and cache 
Open antox
Create a new profile
 Tap on subscribe with toxme unchecked
The app crash.

**Comment by anoadragon453** [comment] 2017-02-08 00:29
Can you provide a LogCat dump of when the crash happened? That would make debugging easier if the developers cannot reproduce your crash on their own devices.

**Comment by zoff99** [comment] 2017-02-08 08:39
this version should write a crash log on your sd card. can you look at that file

**Comment by licaon-kter** [comment] 2017-02-08 09:24
Here's one: https://gist.github.com/licaon-kter/1f19b27c4c5b659d0abf2acf55eb1cb5
F-Droid 0.25.452/3

**Comment by zoff99** [comment] 2017-02-08 11:46
android:onClick does not work on all APIs. what android version do you have on your device?

**Comment by zoff99** [comment] 2017-02-08 11:46
i will make the crashreport logfile diplay more info (like android api and ABI) in the next development version

**Comment by licaon-kter** [comment] 2017-02-08 12:13
6.0.1

**Comment by zoff99** [comment] 2017-02-08 12:19
oh i see: couldn't find "libtox4j-c.so"

where did you download that version of Antox?

**Comment by tweymuth** [comment] 2017-02-08 12:47
I do have the same error message ('couldn't find  "libtox4j-c.so"') with version 0.25.453 of Antox, downloaded from Google Play. Before I updated to this version, Antox worked fine on my phone. I'm running Android 5.1 on a phone with the Qualcomm Snapdragon 200 chipset and a Cortex A7 CPU.

Please let me know if I can provide some more inormation to help you resolve this issue.

**Comment by zoff99** [comment] 2017-02-08 12:49
we need to know what ABI (cpu_abi) you have

this will show you your phones ABI:
https://f-droid.org/repository/browse/?fdid=jackpal.droidexaminer

**Comment by zoff99** [comment] 2017-02-08 12:51
if it works ok with this (development!!) version:
https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25.1

then you need to wait a bit for this to get fixed

**Comment by tweymuth** [comment] 2017-02-08 13:04
Thanks for your quick response!

The ABI of my phone is the following: armeabi_v7a. I will try out the development version as soon as possible and give you feedback.

**Comment by tweymuth** [comment] 2017-02-08 13:13
Indeed, the above development version does work on my phone. I will wait for you to release this version on Google Play. Could you maybe give me a rough time estimate as to when this will be the case?

**Comment by zoff99** [comment] 2017-02-08 13:30
the f-droid version is missing the lib for: armeabi-v7a
possbily the same with the googleplay version.

only @wiiaam can make a new release ...

**Comment by licaon-kter** [comment] 2017-02-08 14:32
Oh, right, official Tox f-droid repo (not F-Droid)

**Comment by zoff99** [comment] 2017-02-08 14:50
offical f-droid guys are not allowing it in the main repo at this time

**Comment by licaon-kter** [comment] 2017-02-08 15:37
Yes, I know, that's why I'm using your (Tox's) repos.

**Comment by Grokafar** [comment] 2017-02-08 17:31
Sorry I forgot to send the crash log... It was on my TODO list ;)
I noticed two different errors so I send two different logs
[crash_2017-02-07_23_29_24.txt](https://github.com/Antox/Antox/files/761446/crash_2017-02-07_23_29_24.txt)
[crash_2017-02-07_23_24_02.txt](https://github.com/Antox/Antox/files/761447/crash_2017-02-07_23_24_02.txt)

**Comment by Grokafar** [comment] 2017-02-08 17:35
I updated to  0.25.453 and the error still the same. 
[crash_2017-02-08_18_24_22.txt](https://github.com/Antox/Antox/files/761461/crash_2017-02-08_18_24_22.txt)

**Comment by Grokafar** [comment] 2017-02-08 17:47
My phone os running on android 6.0.1 and the abi is : armeabi-v7a
I tried the developpement version sent by @zoff99 and it's works !

**Comment by MageSlayer** [comment] 2017-02-08 20:46
I second that.
Version given by @zoff99 works fine for me too.
Please update all public links.

**Comment by zoff99** [comment] 2017-02-09 08:29
@MageSlayer my version is not offical
also be careful with posting crashreport files, they may contain sensitive data!

**Comment by wiiaam** [comment] 2017-02-10 08:20
Fixed in https://github.com/Antox/Antox/commit/2bfcf3162f11567abac94e928fc6391c4a05afc2

**Closed by wiiaam** 2017-02-10 08:20 UTC
